name: C++ Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取完整的提交历史，用于检测文件变更

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Ceedling
        run: gem install ceedling

      - name: Detect changed source files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD | grep '\.c$')
          echo "::set-output name=changed_files::$changed_files"

      - name: Generate unit tests for changed files
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            ceedling new:test --source=$file
          done

      - name: Generate and run all unit tests
        run: ceedling test:all

      - name: Check test results
        if: ${{ failure() }}
        run: |
          echo "Unit tests failed. Please check the logs."
          exit 1
